version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 10
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 40
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 10
  return-statements:
    config:
      threshold: 10
  similar-code:
    enabled: false
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
exclude_patterns:
-  "config/"
-  "db/"
-  "dist/"
-  "features/"
-  "**/node_modules/"
-  "script/"
-  "**/spec/"
-  "**/test/"
-  "**/tests/"
-  "Tests/"
-  "**/vendor/"
-  "**/*_test.go"
-  "**/*.d.ts"
# -  "src/"
# - "**.css"
# - "**.js"
# - "**.html"
- "**/migrations/**"
- "**/tests.py"
- "docs/**"
- "public/**"
- "scripts/**"
- "tests/**"
- "config/**"
