# Generated by Django 2.0.3 on 2018-04-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaysHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_0_2', models.BooleanField()),
                ('hour_2_4', models.BooleanField()),
                ('hour_4_6', models.BooleanField()),
                ('hour_6_8', models.BooleanField()),
                ('hour_8_10', models.BooleanField()),
                ('hour_10_12', models.BooleanField()),
                ('hour_12_14', models.BooleanField()),
                ('hour_14_16', models.BooleanField()),
                ('hour_16_18', models.BooleanField()),
                ('hour_18_20', models.BooleanField()),
                ('hour_20_22', models.BooleanField()),
                ('hour_22_0', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workload', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=50)),
                ('CPF', models.CharField(max_length=20)),
                ('registration', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeekHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorhour.DaysHour')),
            ],
        ),
        migrations.AddField(
            model_name='monthhour',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorhour.WeekHour'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorhour.MonthHour'),
        ),
    ]
