# Generated by Django 2.0.3 on 2018-05-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='subtitle', to='subtitle.Subtitles', verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='doctor', to='doctor.Doctors', verbose_name='doctor'),
        ),
    ]
