# Generated by Django 2.0.3 on 2018-06-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180621_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rule',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
