# Generated by Django 2.0.3 on 2018-05-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
