# Generated by Django 2.0.3 on 2018-06-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.NullBooleanField()),
                ('registration', models.CharField(max_length=50, unique=True)),
                ('CPF', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
